Repository Supervisor/supervisor, pull requests merged in 2022-03, with the labels that each got.

#1410 Add two configuration properties to the getAllConfigInfo method
  supervisor/rpcinterface.py
Labels: xmlrpc

#1347 First cut at fix for #1273.
  supervisor/web.py
Labels: web

#1390 Enhancement on supervisord log severity on process exit status
  supervisor/process.py
Labels: logging
